site_name: Omid Saadat
site_url: https://www.omid-saadat.com
theme:
  name: material
  palette:
    primary: blue

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/godot-background.js